import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { Client } from "../utils/prismicHelpers";
import { RichText } from "prismic-reactjs";
//import { linkResolver } from "../../prismic-configuration";

export default function Home(props) {
  const { data } = props.doc;
  console.log("props", props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.title}>
          <RichText render={data.title} />
        </span>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps({ preview = null, previewData = {} }) {
  const { ref } = previewData;

  const client = Client();

  const doc = (await client.getSingle("homepage", ref ? { ref } : null)) || {};
  /*const menu =
    (await client.getSingle("main_navigation", ref ? { ref } : null)) || {};*/

  return {
    props: {
      doc,
      //menu,
      preview,
    },
  };
}
